Ag develop
dmerkushov/nanoservices pull request #18
Opened 2020-04-06 17:29 UTC by a-petelin

2020-04-07 19:49 UTC, dmerkushov commented on CMakeLists.txt
> +	message(FATAL_ERROR "You cmake it wrong!!")
```suggestion
	message(FATAL_ERROR "Please set FILE or ZOO config")
```

2020-04-07 20:48 UTC, dmerkushov commented on README.md
> +You'll need: `cmake` (minimum version is 3.0), `make`, `libzookeeper-mt2`, local instance of `zookeeper` and a C++11 compiler (the framework is tested with gcc 4.7)
Где взять `libzookeeper-mt2` ? Это название дебиан пакета, а не программного продукта. Он необходим для сборки? А если сборка с FILE?

2020-04-07 20:49 UTC, dmerkushov commented on README.md
> +Also successful build generate misc tool `ns-configurator` at `nanoservices/build/misc/ns-configurator`
```suggestion
A successful build will also generate the `ns-configurator` executable at `nanoservices/build/misc/ns-configurator`
```

2020-04-07 20:49 UTC, dmerkushov commented on README.md
> +For build debian packages from builded sources
```suggestion
To build debian packages from built sources
```

2020-04-07 20:52 UTC, dmerkushov commented on misc/ns-configurator/main.cpp
> +		{'d' , {"delete", 'd', 0, 0, "delete config node at PATH", 1}},
Лучше оставить только реально поддерживаемые на данный момент, остальные закомментировать
```suggestion
//TODO		{'p' , {"path", 'p', "PATH", 0, "Path to config node", 2}},
//TODO		{'a' , {"data", 'a', "DATA", 0, "Data for create or update operation", 2}},
		{'c' , {"create", 'c', 0, 0, "create config node at PATH with DATA", 1}},
		{'r' , {"read", 'r', 0, 0, "read config node data from PATH", 1}},
//TODO		{'u' , {"update", 'u', 0, 0, "update config node at PATH as DATA", 1}},
		{'d' , {"delete", 'd', 0, 0, "delete config node at PATH", 1}},
```

2020-04-07 20:53 UTC, dmerkushov commented on misc/ns-shutdown/main.cpp
> +		{'n' , {"name", 'n', "NAME", 0, "Name for shutdowning service"}},
```suggestion
		{'n' , {"name", 'n', "NAME", 0, "Name of service to shutdown"}},
```

2020-04-07 20:55 UTC, dmerkushov commented on ns-skeleton/CMakeLists.txt
> +endif(FILE)
Лучше директорию `file` не называть :) Чо-нть типа `config_file`, `config_zoo`...

2020-04-07 20:55 UTC, dmerkushov commented on ns-skeleton/CMakeLists.txt
> +endif(FILE)
А зачем два ифа?

2020-04-07 21:10 UTC, dmerkushov requested changes

2020-04-07 21:10 UTC, dmerkushov commented on ns-skeleton/CMakeLists.txt
> +		include_directories(test/file)
Аналогично про имена директорий

2020-04-07 21:10 UTC, dmerkushov commented on ns-skeleton/include/AbstractConfig.h
> +		 */
А что с комментариями случилось? :)

2020-04-07 21:10 UTC, dmerkushov commented on ns-skeleton/include/ConfigValidator.h
> +	 */
Коммент?

2020-04-07 21:10 UTC, dmerkushov commented on ns-skeleton/include/CVInvalidType.h
> +class CVInvalidType : public nanoservices::NsException {
Про эксепшены надо обсудить. Если уж их возвращать, то возвращать везде детальные.

И кстати, почему эти не в неймспейсе?

2020-04-07 21:10 UTC, dmerkushov commented on ns-skeleton/include/NsCmdLineParameters.h
> +		static std::shared_ptr<NsCmdLineParameters> instance () throw (nanoservices::NsException);
```suggestion
		static std::shared_ptr<NsCmdLineParameters> instance() throw (nanoservices::NsException);
```

2020-04-07 21:10 UTC, dmerkushov commented on ns-skeleton/include/NsCmdLineParameters.h
> +		using opt = struct argp_option;
Есть уверенность, что именно `argp_option`?

2020-04-07 21:10 UTC, dmerkushov commented on ns-skeleton/include/ConfigValidator.h
> +	static const int32_t childrenCount = 1024;
Лучше `MAX_CHILDREN_COUNT`

2020-04-07 21:10 UTC, dmerkushov commented on ns-skeleton/src/NsCmdLineParameters.cpp
> +}
М.б. эту функцию в NsUtils?

2020-04-08 01:59 UTC, v-bus commented on ns-skeleton/include/ConfigValidator.h
> +	static const int32_t childrenCount = 1024;
и MAX_DATA_SIZE

2020-04-08 02:00 UTC, v-bus commented on ns-skeleton/src/NsCmdLineParameters.cpp
> +}
питоном повеяло)

2020-04-08 02:05 UTC, v-bus commented on misc/ns-shutdown/main.cpp
> +		{'h' , {"host", 'h', "HOST", 0, "Host of shutdowning service"}},
```suggestion
		{'h' , {"host", 'h', "HOST", 0, "Host of service to shutdown"}},
```

2020-04-08 02:06 UTC, v-bus commented on misc/ns-shutdown/main.cpp
> +		{'p' , {"port", 'p', "PORT", 0, "Port of shutdowning service"}},
```suggestion
		{'p' , {"port", 'p', "PORT", 0, "Port of service to shutdown"}},
```

2020-04-08 02:22 UTC, v-bus commented on misc/ns-shutdown/main.cpp
> +		{'n' , {"name", 'n', "NAME", 0, "Name for shutdowning service"}},
--all из NsSkelRpcRegistry
убить всех наносервисов

2020-04-08 02:29 UTC, v-bus commented on ns-skeleton/include/CVInvalidType.h
> +class CVInvalidType : public nanoservices::NsException {
изначально это исключения конфигуратора, который внешний по отношению к скелетону.
у нас и не определено как инкапсулировать в самом скелетоне исключения. у нас уже 2+ сторонние проекта в коде скелетона, сторонние же не должны знать о скелетоновских исключениях.

2020-04-08 02:41 UTC, v-bus reviewed
third-party/cpp-httplib/fails/a.out а это кто?

2020-04-08 04:32 UTC, a-petelin commented on ns-skeleton/include/NsCmdLineParameters.h
> +		using opt = struct argp_option;
Там коммент старый

2020-04-08 04:39 UTC, a-petelin commented on misc/ns-configurator/main.cpp
> +		{'d' , {"delete", 'd', 0, 0, "delete config node at PATH", 1}},
Что значит реально поддерживаемые?
Всё что надо это написать 3 строки кода про обновление

2020-04-08 04:41 UTC, a-petelin commented on ns-skeleton/CMakeLists.txt
> +endif(FILE)
Решил разбрать по блокам всё что зависит от флага. Иначе там бооольшой if с кучей всего будет.

2020-04-08 04:43 UTC, a-petelin commented on ns-skeleton/src/NsCmdLineParameters.cpp
> +}
Скорее всего, как и извлекалку параметров коммандной строки куда нибудь в NsSkeleton

2020-04-08 04:45 UTC, a-petelin commented on misc/ns-shutdown/main.cpp
> +		{'n' , {"name", 'n', "NAME", 0, "Name for shutdowning service"}},
Тогда он убьёт все общеизвестные в том числе и с других хостов, оно нам надо?

2020-04-08 04:52 UTC, a-petelin commented on README.md
> +You'll need: `cmake` (minimum version is 3.0), `make`, `libzookeeper-mt2`, local instance of `zookeeper` and a C++11 compiler (the framework is tested with gcc 4.7)
`libzookeeper-mt2` это многопоточный клиент для `zookeeper`, в принципе собирается из исходников которые идут с ним.
Если сборка идёт с FILE, то зависимости относящиеся к `zookeeper` естественно не требуются.

2020-04-08 09:36 UTC, a-petelin commented on misc/ns-configurator/main.cpp
> +		{'d' , {"delete", 'd', 0, 0, "delete config node at PATH", 1}},
Добавил выполнение update, завернул всё в try

2020-04-08 09:43 UTC, a-petelin commented on CMakeLists.txt
> +	message(FATAL_ERROR "You cmake it wrong!!")
Поменял сообщение на более понятное

2020-04-08 09:45 UTC, v-bus commented on README.md
>  ```
не все описано.
```
[ 55%] Building CXX object ns-skeleton/CMakeFiles/ns-skeleton.dir/src/zoo/ZooConfig.cpp.o
In file included from /home/v_bus/tmp/nanoservices/ns-skeleton/src/zoo/ZooConfig.cpp:9:
/home/v_bus/tmp/nanoservices/ns-skeleton/include/zoo/ZooConfig.h:2:10: fatal error: zookeeper.h: No such file or directory
 #include <zookeeper.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [ns-skeleton/CMakeFiles/ns-skeleton.dir/build.make:375: ns-skeleton/CMakeFiles/ns-skeleton.dir/src/zoo/ZooConfig.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: ns-skeleton/CMakeFiles/ns-skeleton.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

2020-04-08 10:04 UTC, a-petelin commented on README.md
>  ```
Пофиксил описание зависимостей сборки

2020-04-08 10:22 UTC, v-bus commented on misc/ns-shutdown/main.cpp
> +		{'\0', {0,0,0,0}}
а это что значит \0?

2020-04-08 10:23 UTC, v-bus commented on ns-skeleton/include/AbstractConfig.h
> +		 */
тут типа самодокументруемый код

2020-04-08 10:26 UTC, v-bus commented on ns-skeleton/include/NsUtils.h
> +};
начался фреймворк...
а негде больше больше сплит стибрить?

2020-04-08 10:27 UTC, v-bus commented on ns-skeleton/include/file/FileConfig.h
> +		std::pair<nanoservices::NsSkelJsonPtr, std::string> goThroughPath(const std::string& path, nanoservices::NsSkelJsonPtr nodeobj);
вот тут мне без комментариев непонятно.

2020-04-08 10:28 UTC, v-bus commented on ns-skeleton/include/zoo/ZooConfig.h
> +		static const char delimeter = '/';
тогда уж в дефайн, что ли. А то потеряется

2020-04-08 10:29 UTC, v-bus commented on ns-skeleton/include/zoo/ZooConfig.h
> +		std::vector<char> typedByte = {'\0', '\0', '\0', 's', 'd', 'b'};
и сюда комментарий.

2020-04-08 10:40 UTC, v-bus commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +	_serverptr->Get(R"(/((?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$))", [&](const Request& req, Response& res) {
я не умею читать регексп сложнее .^.+
что там было написано?

2020-04-08 10:42 UTC, v-bus commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +		shared_ptr<string> requestBase64 = make_shared<string>(req.matches[1]);
и сюда коммент

2020-04-08 10:44 UTC, v-bus commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +		// DEBUG
а может нормальное логгирование? у Шандра свой целый кастомный класс есть.

2020-04-08 10:46 UTC, v-bus commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +			res.set_header("Access-Control-Allow-Origin", "*");
а кто прислал? не будем проверять? а то может ходят тут всякие с рест тестилками, хедеров не знают

2020-04-08 10:48 UTC, v-bus commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +	_serverThread = std::thread([&]() {this->_serverptr->listen("0.0.0.0", this->port());});
листен надо дефолт выставить и из конфига читать, нет?

2020-04-08 10:54 UTC, a-petelin commented on ns-skeleton/src/NsCmdLineParameters.cpp
> +}
Функцию перекинул

2020-04-08 10:56 UTC, a-petelin commented on ns-skeleton/include/NsUtils.h
> +};
Неа ... я правда ещё в std::algoritms  не рылся

2020-04-08 10:57 UTC, a-petelin commented on misc/ns-shutdown/main.cpp
> +		{'\0', {0,0,0,0}}
Я тут подумаю, может это будет само добавляться в конструкторе NsCmdLineParameters

2020-04-08 10:57 UTC, a-petelin commented on misc/ns-shutdown/main.cpp
> +		{'\0', {0,0,0,0}}
А в том классе написано зачем оно.

2020-04-08 10:59 UTC, a-petelin commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +	_serverptr->Get(R"(/((?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$))", [&](const Request& req, Response& res) {
Это проверка на то что это валидный base64, т.е. если ткнуться чем-то что нельзя раскодировать в base64 то тебе прийдёт 404, а эта лямбда даже вызвана не будет

2020-04-08 11:13 UTC, v-bus commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +	_serverptr->Get(R"(/((?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$))", [&](const Request& req, Response& res) {
```suggestion
         /**
         * Check request contains base64
         */
	_serverptr->Get(R"(/((?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$))", [&](const Request& req, Response& res) {
```

2020-04-08 11:14 UTC, a-petelin commented on ns-skeleton/CMakeLists.txt
> +endif(FILE)
Переименовал

2020-04-08 11:38 UTC, a-petelin commented on ns-skeleton/include/AbstractConfig.h
> +		 */
Добавил

2020-04-08 11:42 UTC, a-petelin commented on ns-skeleton/include/ConfigValidator.h
> +	static const int32_t childrenCount = 1024;
Переименовал

2020-04-08 11:43 UTC, a-petelin commented on misc/ns-shutdown/main.cpp
> +		{'n' , {"name", 'n', "NAME", 0, "Name for shutdowning service"}},
Давайте на этот ключ отдельную issue  сделаем?

2020-04-08 11:51 UTC, a-petelin commented on misc/ns-shutdown/main.cpp
> +		{'\0', {0,0,0,0}}
Сделал

2020-04-08 11:52 UTC, a-petelin commented on ns-skeleton/include/NsUtils.h
> +};
Пока пусть так будет

2020-04-08 11:52 UTC, a-petelin commented on ns-skeleton/include/zoo/ZooConfig.h
> +		static const char delimeter = '/';
Думаю не стоит

2020-04-08 11:54 UTC, a-petelin commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +		// DEBUG
Это остатки того что было до этого у Шандра, в принципе надо с ним обсудит

@dmerkushov и что нам с этим делать?

2020-04-08 12:04 UTC, a-petelin commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +	_serverThread = std::thread([&]() {this->_serverptr->listen("0.0.0.0", this->port());});
Теперь он читается из конфига

2020-04-08 14:48 UTC, a-petelin commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +			res.set_header("Access-Control-Allow-Origin", "*");
Сейчас их в 90% случаев пошлёт, позже будет добавлены проверки не только на отправителя.

2020-04-08 15:07 UTC, a-petelin commented on ns-skeleton/include/file/FileConfig.h
> +		std::pair<nanoservices::NsSkelJsonPtr, std::string> goThroughPath(const std::string& path, nanoservices::NsSkelJsonPtr nodeobj);
Добавил

2020-04-08 15:07 UTC, a-petelin commented on ns-skeleton/include/zoo/ZooConfig.h
> +		std::vector<char> typedByte = {'\0', '\0', '\0', 's', 'd', 'b'};
Тоже

2020-04-08 15:07 UTC, a-petelin commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +		shared_ptr<string> requestBase64 = make_shared<string>(req.matches[1]);
+

2020-04-09 11:01 UTC, dmerkushov commented on misc/README.md
> +Tool for work with nanoservices config
Подробнее надо

2020-04-09 11:02 UTC, dmerkushov commented on misc/ns-configurator/VERSION.txt
> +0.1
Давай версию ту же, что и у либы. Может, даже свой VERSION файл не нужен

2020-04-09 11:08 UTC, dmerkushov commented on misc/testService/testMethod.h
> +	std::shared_ptr<TestMethodResult> processRequest(std::shared_ptr<TestMethodArgs> args) throw(nanoservices::NsException);
```suggestion
	std::shared_ptr<TestMethodResult> processRequest(std::shared_ptr<TestMethodArgs> args) noexcept(false);
```

Боюсь, придётся соответствовать общепринятой практике

2020-04-09 11:10 UTC, dmerkushov commented on ns-skeleton/FindNanoservices.cmake
> +	OUTPUT_VARIABLE SKELETON_LIB_DEB)
```suggestion
execute_process(
	COMMAND dpkg-query -W -f=\${Package}\\tProvides:\${Provides}\\n
	COMMAND grep -E "nanoservices$"
	COMMAND sed -e "s/\\\(.*\\\)\\t.*/\\1/"
	OUTPUT_VARIABLE SKELETON_LIB_DEB
)
```

2020-04-09 11:11 UTC, dmerkushov commented on ns-skeleton/include/AbstractConfig.h
> +		 *   All subnodes delete too.
```suggestion
		 *   All subnodes will be deleted too.
```

2020-04-09 11:11 UTC, dmerkushov commented on ns-skeleton/include/AbstractConfig.h
> +		 * Get instance of current realisation of AbstractConfig
```suggestion
		 * Get instance of currently configured implementation of AbstractConfig
```

2020-04-09 11:12 UTC, dmerkushov commented on ns-skeleton/include/AbstractConfig.h
> +		 * Initialisation connection to config source
```suggestion
		 * Connect to the configuration source
```

2020-04-09 11:13 UTC, dmerkushov commented on ns-skeleton/include/AbstractConfig.h
> +		 * Initialisation connection to config source
Может, и метод `connect()` назвать?

2020-04-09 11:13 UTC, dmerkushov commented on ns-skeleton/include/AbstractConfig.h
> +		 * Update config node at path use data
```suggestion
		 * Update config node at path using the given data
```

2020-04-09 11:14 UTC, dmerkushov commented on ns-skeleton/include/AbstractConfig.h
> +		 *   If data define subnodes, they created too
```suggestion
		 *   If data has subnodes, they are created too
```

2020-04-09 11:15 UTC, dmerkushov commented on ns-skeleton/include/CVInvalidType.h
> +class CVInvalidType : public nanoservices::NsException {
Я не про неймспейс скелетона (которого нет), я про неймспейс `nanoservices`, который для всего этого проекта

2020-04-09 11:17 UTC, dmerkushov commented on ns-skeleton/include/ConfigValidator.h
> +	 * @param data
```suggestion
	 * Valide configuration data
	 *   By now, checks are:
	 *    - count of subnodes at one node
	 *    - size of node data 
	 *    - using appropriate types for define node data
	 *    - definition of data for leaf subnodes
	 * @param path used only to generate error messages
	 * @param data
```

2020-04-09 11:23 UTC, dmerkushov commented on ns-skeleton/include/NsCmdLineParameters.h
> +		using opt = struct argp_option;
По-моему, стоит этот `uses` наружу вынести и использовать `opt` ещё и в `getOptionDefinitions()`

2020-04-09 11:29 UTC, dmerkushov commented on ns-skeleton/include/NsSkelRpcServer.h
> +		std::atomic<bool> _serverActive;
То есть я понимаю, что это сюда вытащено для того, чтобы дать детям доступ к этим полям. Но имхо если им нужен доступ, лучше дать им геттеры-сеттеры.

2020-04-09 11:32 UTC, dmerkushov commented on ns-skeleton/include/NsSkelRpcService.h
> +		NsSkelRpcService(std::shared_ptr<std::string> serviceName, NsSkelJsonPtr serviceJson) throw(NsException);
Не уверен, что сюда стоит сервис нейм пихать, а не чиать его из джсона

2020-04-09 11:34 UTC, dmerkushov commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
Сюда бы ещё `JSON_ARRAY`, у которого тоже дети есть

2020-04-09 11:35 UTC, dmerkushov commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_NULL:
А чо раньше скобочки есть, а тут нету? :)

2020-04-09 11:38 UTC, dmerkushov commented on ns-skeleton/src/NsSkelConfiguration.cpp
> +
Строчка лишняя)

2020-04-09 11:40 UTC, dmerkushov commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +	_serverptr->Get(R"(/((?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$))", [&](const Request& req, Response& res) {
Это коммент в коде, а не документационный. Поэтому надо не `/**`, а `/*` или `//`

2020-04-09 11:45 UTC, dmerkushov commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +		// DEBUG
Лучше закомментировать. Это при отладке RPC нужно

2020-04-09 11:58 UTC, dmerkushov commented on ns-skeleton/src/file_config/FileConfig.cpp
> +		throw NsException(NSE_POSITION, "Path must start from \'/\'!");
```suggestion
		throw NsException(NSE_POSITION, "Path must start with \'/\'!");
```

2020-04-09 12:01 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +		// Extract data from 2nd parentsizes
```suggestion
		// Extract data from 1st parentheses
		host = pieces_match[1].str();
		// Extract data from 2nd parentheses
```

2020-04-09 12:05 UTC, a-petelin commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
JSON_ARRAY не поддерживается пока

2020-04-09 12:06 UTC, a-petelin commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_NULL:
Переменные не объявляются

2020-04-09 12:06 UTC, a-petelin commented on ns-skeleton/include/NsSkelRpcServer.h
> +		std::atomic<bool> _serverActive;
Можно вернуть

2020-04-09 12:07 UTC, a-petelin commented on ns-skeleton/include/AbstractConfig.h
> +		 * Initialisation connection to config source
Но с файлом то он connect не делает

2020-04-09 12:08 UTC, a-petelin commented on misc/ns-configurator/VERSION.txt
> +0.1
Этот файлик удалить забыл, я пробовал  покомпонентно назначать версии, но это не работает

2020-04-09 12:10 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
Мдяя...

2020-04-09 12:10 UTC, a-petelin commented on misc/README.md
> +Tool for work with nanoservices config
Это чтобы не пустой коммитить. Что писать я понятия не имею. Накидайте что вам не хватает знать и я распишу.

2020-04-09 12:11 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +			connect_wait.set_exception(make_exception_ptr(NsException(NSE_POSITION, "Coudn't connect to zookeeper!")));
```suggestion
			connect_wait.set_exception(make_exception_ptr(NsException(NSE_POSITION, "Couldn't connect to zookeeper!")));
```

2020-04-09 12:11 UTC, a-petelin commented on misc/testService/testMethod.h
> +	std::shared_ptr<TestMethodResult> processRequest(std::shared_ptr<TestMethodArgs> args) throw(nanoservices::NsException);
Ни вапрос, пройдусь везде и заменю.

Кстати auto_ptr тоже deprecated а в msgpack-c он есть. Возможно это изза директивы про Cxx03

2020-04-09 12:12 UTC, a-petelin commented on ns-skeleton/FindNanoservices.cmake
> +	OUTPUT_VARIABLE SKELETON_LIB_DEB)
Не понял что поменяно ...

2020-04-09 12:13 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	int timeoutms = 3000;
Я даже больше скажу: не на константу надо заменить, а на параметр конфигурации

2020-04-09 12:13 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +		path += delimeter + p;
`delimiter` через **i**

2020-04-09 12:14 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
Это чистая заглушка. Надо принять решение что делать с тем логом что генерит либа общения с zookeeper.

2020-04-09 12:14 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	case JSON_OBJECT: {
Опять про `JSON_ARRAY` забыли )

2020-04-09 12:15 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	int timeoutms = 3000;
Не уверен. Это чисто магия, для того чтобы не долбиться полчаса в пингуемый хост где zookeeper отсутствует.

2020-04-09 12:15 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	case JSON_OBJECT: {
См. выше

2020-04-09 12:16 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	auto child_v_f = child_v_p.get_future();
`v_p`, `v_f` ... Попонятнее бы

2020-04-09 12:16 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	auto child_v_f = child_v_p.get_future();
Promise и его future

2020-04-09 12:16 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +		ess <<  "Data at \"" << path << "\" corrupted or used unknown type specifier!";
```suggestion
		ess <<  "Data at \"" << path << "\" is corrupt or uses an unknown type specifier!";
```

2020-04-09 12:17 UTC, dmerkushov requested changes

2020-04-09 12:17 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	case JSON_OBJECT: {
Ну а как же `JSON_ARRAY`?

2020-04-09 12:18 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	case JSON_OBJECT: {
См. выше

2020-04-09 12:23 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	int timeoutms = 3000;
Я понимаю, зачем эта магия, но таймауты нужны не только для того чтобы не долбиться туда, где сервис мёртв, но и чтобы закрывать сетевые лаги. Если зукипер в какой-то инсталляции либо отвечает за 100 мс, либо не отвечает никогда, то ставить таймаут 3000 мс может быть расточительно, пусть лучше наши сервисы умирают поскорее: раньше на приборах станет видно. Так что это должно конфигуриться, по-моему. Как дефолт 3000 норм, разумеется

2020-04-09 12:24 UTC, a-petelin commented on ns-skeleton/include/NsSkelRpcService.h
> +		NsSkelRpcService(std::shared_ptr<std::string> serviceName, NsSkelJsonPtr serviceJson) throw(NsException);
Сервис нейма теперь нет в этом json

2020-04-09 12:25 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
Ну, прям как хорошо бы было - это гнать лог зукипера в какой-то поток в памяти, а потом этот поток засовывать в наш логгер по мере поднятия соединения с ним

2020-04-09 12:27 UTC, dmerkushov commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
Всё равно бы его сюда добавить закомменченный с тудушкой и пояснением

2020-04-09 12:28 UTC, dmerkushov commented on ns-skeleton/include/AbstractConfig.h
> +		 * Initialisation connection to config source
Он коннектится к источнику конфигурации ^)

А что источник файловый, ну так он файловый

2020-04-09 12:28 UTC, dmerkushov commented on ns-skeleton/FindNanoservices.cmake
> +	OUTPUT_VARIABLE SKELETON_LIB_DEB)
> Не понял что поменяно ...

Скобочки-табуляции

2020-04-09 12:30 UTC, dmerkushov commented on misc/README.md
> +Tool for work with nanoservices config
Чего тут не хватает... Как его юзать - не хватает. И ссылки из главного ридми сюда, чтобы при взгляде оттуда было видно, где про конфигурирование рассказано

2020-04-09 12:55 UTC, a-petelin commented on misc/README.md
> +Tool for work with nanoservices config
Ссылка из главного readme есть

2020-04-09 12:56 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	int timeoutms = 3000;
Тут всё сложнее чем ты посчитал.

2020-04-09 13:02 UTC, a-petelin commented on ns-skeleton/include/NsCmdLineParameters.h
> +		using opt = struct argp_option;
В принципе вариант ...

2020-04-09 13:05 UTC, a-petelin commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +	_serverptr->Get(R"(/((?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$))", [&](const Request& req, Response& res) {
Я заделал свой вариант и там просто многострочный

2020-04-09 13:07 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
Для этого надо придумать как получить файловый дескриптор на этот поток ....

2020-04-09 13:07 UTC, v-bus commented on ns-skeleton/src/NsSkelRpcHttpServer.cpp
> +	_serverptr->Get(R"(/((?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$))", [&](const Request& req, Response& res) {
да, этот мой)

2020-04-09 13:10 UTC, v-bus commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
это @dmerkushov философский вопрос, как совать в ветку массивы. надо придумать кодировку
мы думали, может у тебя будут идеи

2020-04-09 13:13 UTC, v-bus commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
@a-petelin так это настройка zookeeper самого или zoo.h? 
@dmerkushov  я так понял, что это настройка для локально установленного зукипера и кроме дебага не имеет смысла
и мне не нравится закоменченный дебаг строки. это срр у вас тут все равно все в макросах

2020-04-09 13:14 UTC, v-bus commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	int timeoutms = 3000;
управление таймаутами это отдельный геммор. Давайте в конфиг.

2020-04-09 20:04 UTC, dmerkushov commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
@a-petelin 
> Для этого надо придумать как получить файловый дескриптор на этот поток
* файловая система в памяти
* `/tmp`
* named pipe

@v-bus что такое "закомменченный дебаг строки"? :)

2020-04-09 20:07 UTC, v-bus commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
@a-petelin ну Шандр предлагал оставить кусок отработки RPC //DEBUG в комментариях

2020-04-09 20:07 UTC, dmerkushov commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
А чем не подходит:
"0" -> нулевой элемент
"1" -> первый
...

2020-04-09 20:08 UTC, dmerkushov commented on ns-skeleton/include/NsSkelRpcService.h
> +		NsSkelRpcService(std::shared_ptr<std::string> serviceName, NsSkelJsonPtr serviceJson) throw(NsException);
А почему теперь нету?

2020-04-09 20:09 UTC, v-bus commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
Вот и добавь свой вариант. Мы пока без JSON_ARRAY обходимся, строк хватает. Если ты считаешь, что он щас нужен - добавь с логикой.

2020-04-09 20:13 UTC, v-bus commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
мы сделали ограничения, ты видел, что детей не более 1024, в каждом листике не больше 1 Мб байтовый данных. 1Мб - рекомендация зукипера, ему так проще синхронизоваться. Поэтому просто засунуть массив в листик, значит, проверять в валидаторе, что он меньше 1Мб., а если резать ветками, то массив станет не больше 1024 элементов. Хотя это конфиги, и хрен знает, для чего больше массив использовать.

2020-04-09 20:13 UTC, dmerkushov commented on README.md
> +More info about [here](/misc/README.md)
Напиши плз конкретно, что там есть тулза для конфигурирования и для старта-останова. А подробности читайте там-то

2020-04-09 20:19 UTC, v-bus commented on ns-skeleton/include/NsSkelRpcService.h
> +		NsSkelRpcService(std::shared_ptr<std::string> serviceName, NsSkelJsonPtr serviceJson) throw(NsException);
Мыж хотели какие-то другие вариаты lookup service делать. Я помню только те варианты, что мы с Лехой обсуждали, но там json в качестве диспатчера не было.

2020-04-09 20:20 UTC, dmerkushov commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
Я не знаю, зачем он может понадобиться. Если понадобится - можно будет сделать так, как понадобится. Но когда я читал исходники, у меня возникло ощущение, что про него просто забыли. На данный момент достаточно было бы написать комментарий, что массив не поддерживаем, и в сообщении об ошибке об этом тоже честно говорить.

2020-04-09 20:21 UTC, v-bus commented on README.md
> +More info about [here](/misc/README.md)
Дорогая редакция, сам нажми кнопку insert a suggestion и напиши. все равно потом будешь редактировать, что два раза мучаться.

2020-04-09 20:24 UTC, v-bus commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
@a-petelin добавь JSON_ARRAY 1024 max element и 1Mb each element. И пусть портиться. Вдруг мы тут timeline начнем хранить эталонный.

2020-04-10 06:57 UTC, a-petelin commented on ns-skeleton/include/NsSkelRpcService.h
> +		NsSkelRpcService(std::shared_ptr<std::string> serviceName, NsSkelJsonPtr serviceJson) throw(NsException);
В этом json нет имени потому что этот json теперь извлекается из словаря по имени сервиса а не из массива

2020-04-10 06:59 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
@v-bus этот лог это выхлоп библиотеки что ходит к `zookeeper`

2020-04-10 07:00 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	int timeoutms = 3000;
Конкретно этим таймаутом я бы не управлял. Тут словами рассказывать надо, а не писать буквами больше чем я уже кода написал.

2020-04-10 07:37 UTC, a-petelin commented on README.md
> +More info about [here](/misc/README.md)
И так каждую тулзу сюда прописывать?

2020-04-10 07:39 UTC, a-petelin commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
Проще добавить в других местах выдачу исключения если `JSON_ARRAY` встретился

2020-04-10 10:33 UTC, a-petelin commented on misc/ns-configurator/VERSION.txt
> +0.1
Удалено

2020-04-10 11:02 UTC, a-petelin commented on misc/testService/testMethod.h
> +	std::shared_ptr<TestMethodResult> processRequest(std::shared_ptr<TestMethodArgs> args) throw(nanoservices::NsException);
`noexcept(false)` в принципе указывать не надо, т.к. компилятору пофиг.

А вот `noexcept(true)` там где необходимо стоит указать

2020-04-10 13:06 UTC, dmerkushov commented on README.md
> +More info about [here](/misc/README.md)
```suggestion
By now, these are tools for configuring nanoservices (ns-configurator) and shutdowning a started nanoservice remotely (ns-shutdown). [More info](/misc/README.md)

It is recommended to use the supplied tools to configure nanoservices, as different configuration source strategies may be applied by the nanoservice hosting teams.
```

2020-04-10 17:48 UTC, a-petelin commented on misc/testService/testMethod.h
> +	std::shared_ptr<TestMethodResult> processRequest(std::shared_ptr<TestMethodArgs> args) throw(nanoservices::NsException);
Сделал

2020-04-29 16:56 UTC, a-petelin commented on ns-skeleton/src/ConfigValidator.cpp
> +	case JSON_OBJECT: {
Добавил
https://github.com/dmerkushov/nanoservices/pull/18/commits/f20c33bf1f255471e28ffad7a596421a5d764111

2020-04-29 16:56 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	case JSON_OBJECT: {
Добавил
https://github.com/dmerkushov/nanoservices/pull/18/commits/f20c33bf1f255471e28ffad7a596421a5d764111

2020-04-29 16:57 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	case JSON_OBJECT: {
Добавил
https://github.com/dmerkushov/nanoservices/pull/18/commits/f20c33bf1f255471e28ffad7a596421a5d764111

2020-04-29 17:05 UTC, a-petelin commented on ns-skeleton/include/NsSkelRpcServer.h
> +		std::atomic<bool> _serverActive;
Вроде решили что закрываем

2020-04-29 17:06 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	zoo_set_log_stream(log_fp_);
В итоге решили завести отдельный issue, там обсудить и делать как решили

2020-04-29 17:06 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +	int timeoutms = 3000;
В итоге решили завести отдельный issue, там обсудить и делать как решили

2020-04-29 17:08 UTC, a-petelin commented on ns-skeleton/src/zoo_config/ZooConfig.cpp
> +		path += delimeter + p;
Готово

2020-05-24 13:17 UTC, merged